# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginlogout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_loginlogout(self):
    self.driver.get("http://localhost:8000/auth/login/?next=/dashboard/")
    self.driver.set_window_size(1088, 709)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("admin")
    self.driver.find_element(By.ID, "submit-id-submit").click()
    self.driver.find_element(By.LINK_TEXT, "Test admin Admin").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
